---
title: 'Preparación'
teaching: 10
exercises: 2
---

:::::::::::::::::::::::::::::::::::::: questions 

- ¿Qué elementos componen una clase bien preparada?

- ¿Cómo podemos mejorar nuestras clases a través de la práctica?

- ¿Qué rol cumple la retroalimentación en este proceso?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Desarrollar habilidades para planificar y practicar clases en comunidad.

- Aplicar rúbricas de retroalimentación en presentaciones docentes.

- Entrenar estrategias para la mejora progresiva de la enseñanza en vivo.

::::::::::::::::::::::::::::::::::::::::::::::::

## Preparándote para Enseñar

### Programación en Vivo - Ronda 2

Tuvieron una primera oportunidad de practicar explicando algo de Carpentries en 2 minutos. Como dijimos antes, esta habilidad se aprende con práctica y podemos mejorar usando el feedback de nuestros colegas y estudiantes. Vamos a probar eso ahora.

Pero además queremos presentarles esta rúbrica:

| **Positivo** | **Negativo** |             |
|--------------|--------------|-------------|
|              |              | **Contenido**    |
|              |              | **Interacción**  |
|              |              | **Presentación** |

Esta rúbrica es la que usamos durante las demos, y en esta segunda vuelta de programación en vivo tienen la chance de 

- Usarla para darle feedback a sus colegas
- Tener en cuenta las cosas que miramos para incorporarlas en sus clases. 

::::::::::::::::::::::::::::::::::::: challenge 

## Ejercicio en grupo

1. Revisen el feedback que les dieron sus colegas e identifiquen algo que les gustaría mejorar

2. Cada persona enseñará lo mismo que en la práctica anterior en 2 minutos y el resto tomará notas usando la rúbrica 3x2 en el documento compartido

Si les queda tiempo, pueden hacer una ronda de comentarios sobre lo que vieron. 

Tiempo para la actividad: 25 minutos.

::::::::::::::::::::::::::::::::::::::::::::::::

### Aprendemos a enseñar

Aunque enseñar a veces parezca intuitivo, como toda habilidad, podemos aprender a cómo hacerla y cómo mejorarla.

Este desarrollo de nuestras habilidades docentes es permanente e incluye la preparación antes, durante y después de las clases. 

La preparación debe ser completa, teniendo en cuenta los contenidos técnicos que van a enseñarse y también la forma en que tus estudiantes van a recibir esos contenidos, procesarlos y aprenderlos. 

La mayoría de las personas diseñan lecciones sobre temas que aprendieron hace mucho, empezando con algunas diapositivas para explicar lo que saben, agregando unas semanas después una tarea basada en esos contenidos, y repitiendo estos pasos cada semana hasta la madrugada anterior al examen final, cuando se prometen a sí mismas que la próxima vez sí o sí serán más organizadas. 

Esto no es muy efectivo. Hay otro método (conocido como reingeniería) que nos ayuda a mantener la enseñanza enfocada en sus objetivos.

## Antes del Curso o Clase

### Elegir entre estudiantes tipo

En primer lugar, para enseñar primero necesitamos conocer a quién vamos a tener adelante, quiénes son nuestros estudiantes. 

Dependiendo de si dan clases en distintos ámbitos (escuela secundaria, una materia en la universidad o talleres cortos), su público va a cambiar. 

En este punto entran en juego los estudiantes tipo que crearon. 

Para cada curso definirán quiénes son sus estudiantes tipo, qué problemas pueden llegar a tener y cómo el curso puede ayudarles. 

Greg Wilson recomienda tener una media docena y elegir entre esos estudiantes a quienes van a dar clases cada vez que va a desarrollar un curso.

En https://metadocencia.org/personas/ pueden encontrar algunos ejemplos.

### Repasa tus objetivos de aprendizaje

El segundo paso es definir los objetivos de aprendizaje. Normalmente queremos empezar a preparar material, pero si no tenemos claros los objetivos, es posible que perdamos el rumbo en el camino o que tal vez incluyamos material que en realidad no era necesario.

Estos objetivos de aprendizaje tienen que ser bien específicos y al mismo tiempo darnos información (y a los estudiantes) sobre de qué va la cosa, para asegurar que todos/as tus estudiantes tengan el mismo entendimiento de lo que se supone que una lección debe lograr.

Cuando se trata de elegir verbos para definir los objetivos de aprendizaje, la mayoría de los/las docentes usan la taxonomía de Bloom, que nos da un marco para discutir los distintos niveles de comprensión. Su forma más reciente tiene seis categorías, organizadas jerárquicamente. Son descritas con verbos como **recordar**, o yendo un paso más allá, **comprender**, luego **aplicar** lo comprendido para la resolución de problemas, **analizar** la información para identificar causas y hacer inferencias, **evaluar** opiniones o ideas y **crear** para proponer soluciones alternativas. 

::::::::::::::::::::::::::::::::::::: instructor 

Aunque la taxonomía de Bloom aparece en casi todos los libros de texto sobre educación, acá no le damos mucha relevancia porque hay evidencia de que incluso educadores con mucha experiencia tienen problemas para ponerse de acuerdo en cómo clasificar específicamente algunas cuestiones. 

:::::::::::::::::::::::::::::::::::::

Aquí más material sobre esta Taxonomía https://carpentries.github.io/instructor-training/15-lesson-study/index.html

### Repasar cómo van a determinar que sus estudiantes alcanzaron esos objetivos

Una vez que definimos los objetivos de aprendizaje, tenemos que pensar cómo vamos a determinar si nuestra audiencia aprendió, si alcanzó esos objetivos. 

Acá, hagamos una diferencia. Un objetivo de aprendizaje es lo que una lección se esmera por lograr. Un resultado de aprendizaje es lo que realmente se logra, es decir, el resultado concreto, lo que las personas asistentes realmente se llevan. 

Y en este punto entonces entran en juego, primero, las evaluaciones formativas, que no solo nos ayudan a nosotros como docentes, sino que también permiten ser más conscientes de lo que las personas están aprendiendo (motivación, metacognición - un paso a ser autónomos en el aprendizaje).

Finalmente, el rol de la evaluación sumativa puede ser, por lo tanto, comparar resultados de aprendizajes con objetivos de aprendizajes.

> No basta con preguntar. Recordemos esto que hablábamos el otro día, acerca del Efecto Dunning-Kruger. En general, no somos nada buenos evaluando cuánto aprendimos. Si simplemente preguntamos “Se entendió”, es posible que nos perdamos gran parte de la historia. Por eso, es verdaderamente importante establecer cómo vas a determinar que tus estudiantes alcanzaron los objetivos, tanto al final de un segmento, como de la lección, o del curso.

### Define el contenido

Y ahora sí, podemos definir el contenido que les permita llevar a sus estudiantes de una evaluación formativa a otra.
 
Esto que discutimos hasta acá se llama Diseño Reverso de una lección.

### Acordar estrategia con co-docente/ayudante

Ahora ya tienen su clase. Si tienen la suerte, la posibilidad de no enseñar solo o sola, definan cómo vas a trabajar con sus colegas. Dividan las tareas a realizar antes, durante y después del curso. Recuerden avisarles a sus estudiantes quién será su ayudante y cómo puede ayudar cada una de las docentes y ayudantes antes, durante y después de la clase.

### Conocer a sus estudiantes

Antes de cada curso, es necesario conocer a sus estudiantes. Pregúntenles sobre su situación personal, respetando su privacidad, pero intentando recolectar la información necesaria para planificar mejor la clase. 
Cuestiones de conocimiento previo: ¿qué materias cursaron? 
Cuestiones técnicas: ¿Tienen internet? ¿Tienen una computadora? ¿Con cámara y micrófono? ¿Usan normalmente Zoom? 
Cuestiones de accesibilidad: ¿Tienen alguna de las dificultades previstas para acceder a los contenidos del curso? ¿Cuáles de las soluciones que podrían ofrecerles serían de ayuda?

Lo más importante es que no asumas nada sobre tus estudiantes, ni siquiera sobre la base de cursos previos.

::::::::::::::::::::::::::::::::::::: challenge 

## Ejercicio 

Pensando en qué pueden enseñar en 5-10 minutos:

- Definan un objetivo de aprendizaje y cómo evaluarías que se alcanzó

Escriban su objetivo y cómo evaluarlo en el documento compartido

::::::::::::::::::::::::::::::::::::::::::::::::

## Al comenzar el curso

### ¿Cómo generar un ambiente de aprendizaje positivo?

Llegamos al principio del curso. Es el primer día y nos preguntamos, ¿cómo generar un ambiente de aprendizaje positivo desde el principio?

Una de las primeras cosas que podemos hacer es pensar cómo vamos a presentarnos y cómo vamos a presentar el curso. Esto va a marcar el tono, el ambiente del curso, ya sea de un cuatrimestre entero o algo cortito (¡sobre todo si es corto!). 

::::::::::::::::::::::::::::::::::::: challenge 

## Ejercicio en grupo

Piensen:

- ¿Qué buscan lograr cuando se presentan a sus estudiantes?
- ¿Qué información deben incluir para lograrlo?

Una persona por grupo resumirá en el documento compartido lo que charlen 

::::::::::::::::::::::::::::::::::::::::::::::::

No creemos en el amor a primera vista, pero sabemos que la primera impresión perdura. Aunque hay estudios sobre cómo juzgamos la apariencia y el entorno, no nos detendremos en ellos. Sí creemos que es importante saludar a nuestros estudiantes cuando van llegando, darles la bienvenida. 

Comencemos con presentarnos, con más o menos formalidad según sea nuestro estilo. Piensa: ¿Qué características queremos resaltar de nosotros mismos? ¿Qué cosas hicimos y nos prepararon para enseñar? ¿Por qué lo hacemos? También reflexionemos sobre qué no deberías decir. Si nos consideramos una persona experta, contemos un poco cómo llegamos a donde llegamos. También lo que tenemos en común con nuestra audiencia. El objetivo es hacernos más accesible.

Aclaremos objetivos y expectativas. Es necesario que todo el mundo esté en la misma página

Las/los estudiantes también pueden presentarse. En una clase de 10 o 12 personas, se puede hacer verbalmente; en una clase más grande o si aún no se conocen entre sí, quizás es mejor que cada estudiante escriba una o dos líneas sobre sí en el documento compartido. Además, para conocer a sus estudiantes, y ayudar a que se conozcan entre sí, nada mejor que un ejercicio “Ice breaker”.

Mientras contamos todo esto, aprovechemos para establecer el tono de las clases. 
- ¿Cómo van a trabajar? 
- ¿Cuáles son las pautas de convivencia? 
- ¿Cómo pediremos e incorporaremos feedback? 
- ¿El intercambio será totalmente informal o cuidaremos cierta formalidad? 
- ¿Permitiremos que nos interrumpan con consultas o indicaremos desde el principio que vayan quedando escritas en el documento compartido y las abordaremos al final de la exposición? 

Dirijan el tránsito, pero recuerden mantenerse accesibles y buscar la motivación para aprender en todo momento. 

Lo mejor de todo esto es que tener organizada y pensada la introducción, nos ayudará a estar menos nerviosa (al menos a mi) y te ayuda a arrancar sin la “página en blanco”.

Luego de una introducción nuestra audiencia debería:

- Creer que estamos preparados para enseñar 
- Tener una idea de como va a llevarse a cabo las clases
- Saber que se va a enseñar
- Saber que se les va a pedir
- ¡Tener ganas de empezar a aprender!

### En Cada Unidad de Estudio, y al Final

Luego de la clase (o al final) pidamos crítica. Anónima, individual y breve

Hasta ahora nos concentramos en el feedback entre colegas. Herramientas parecidas se pueden usar para conocer el parecer de sus estudiantes. 

A tener en cuenta:
- No nacemos sabiendo dar crítica
- No pidamos crítica si no vamos a aplicarla
- Si no vamos a aplicarla, informemos por qué no

#### Otras formas para pedir Feedback

Practicamos mucho dar y recibir feedback entre colegas, también mencionamos pedir feedback a nuestros estudiantes. Estas son algunas ideas para hacerlo.

- Usar notas adhesivas de colores para identificar cuando terminaron un ejercicio y cuando tienen problemas. 

- Esas notas adhesivas también pueden servir para dejar comentarios anónimos antes del almuerzo o al final de la jornada. Como docente, pueden dar pautas acerca de qué aspectos positivos o negativos resaltar. Por ejemplo, en el verde escribir algo importante que aprendieron hoy, en el rojo algo que resultó confuso y tendrían que revisar.

- Pedir feedback en vivo al final de la clase, que cada persona por turno mencione algo positivo (pulgar para arriba) o negativo (pulgar para abajo) según le toque. La regla es que no pueden repetir comentarios, eso les obligará a pensar más y no caer en los comentarios más amigables y seguros. Lo importante es no comentar sobre el feedback en el momento, agradézcanlo y denle tiempo a procesarlo antes de responder o cambiar nada en tu clase.

- Formulario de fin de clase, puede ser tan sencillo como el que usamos en MetaDocencia, algo para mantener, algo para mejorar. Anónima y cortita. La clave está en dedicar los últimos minutos de la clase a que respondan el formulario, de esa manera habrá más chances de que todo el mundo lo complete. 

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: instructor

### Pausa

No se desconecten, pero sí aléjense de pantallas.

Volvemos en 10 minutos.

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

## Enseñando online
### Tomar las riendas

> En la realidad, pasará todo lo que no impidas que pase. En la virtualidad, solo pasará lo que permitas que pase. (Daniel Dennett, Is evolution an algorithmic process?)

Y esta es una diferencia fundamental entre un ambiente real y un ambiente virtual. En el mundo real va a pasar de todo a menos que expresamente traten de impedirlo. En el mundo virtual solo va a pasar lo que programen expresamente.

En el aula real los alumnos pueden interactuar, mirarse, charlar en los pasillos a menos que hagas algo para impedirlo. En el aula virtual, no van a tener ninguna interacción que no generes expresamente. 

Además del componente cognitivo, en las clases hay un componente social. Mucha gente odia de lo virtual esta incapacidad para mantener lo social, que debe generarse.

Gran parte del desafío de dar clases virtuales radica en que hay que ser mucho más intencional a la hora de generar los intercambios que en la presencialidad surgen más naturalmente.

### Usar salas de trabajo

> Trabajar en grupos pequeños facilita la instrucción entre pares y mantiene la atención

Lo ideal sería tener clases privadas, por supuesto, pero esto no escala. Así que las salas de trabajo emulan la presencialidad un poquito mejor. Suelen gustar mucho a quienes participan de MetaDocencia.

Usemos las salas de trabajo para grupos que ofrecen Zoom o Meet (incluso en su versión gratuita). La instrucción entre pares es la práctica de enseñanza escalable más efectiva que conocemos. Se basa en que sus estudiantes debatan sus respuestas a una pregunta motivadora durante dos o tres minutos. Las salas para grupos de Zoom hacen que esto sea relativamente fácil de ejecutar en línea: toma de 15 a 30 segundos llevar a todos a las salas, y en una clase de cuarenta habrá uno o dos que inicialmente tengan problemas, pero hace mucho para mantener a tus estudiantes con buena motivación y atención. 

El “número mágico” es de 3 o hasta 4 participantes por sala, pues de incluir más se empiezan a hacer subgrupos, o alguien no participa.

### Compartir el trabajo en tiempo real

Hagan que sus estudiantes compartan su trabajo en un Google Doc, HackMD o Etherpad durante la clase. Si usan documentos compartidos como el que usamos en este taller, copia una lista con los nombres de las personas para que sepan dónde escribir. Comiencen con algún ejercicio simple (como el de escribir nombres); esto ayuda a familiarizarse.

Una vez que se sientan cómodas con esto (lo que llevará unas horas), haz que tomen notas compartidas en el mismo documento. Esto, además de un gran servicio de apuntes colectivos para toda la clase, ayudará durante y luego de la clase para asegurarse de que los conceptos que buscas enseñar fueron entendidos como esperabas.

Dependiendo del perfil de sus estudiantes, podría ser mejor no implementarlo desde el comienzo, pues puede ser apabullante ver escribir a muchas personas a la vez. Pero tras una o dos clases, se puede volver una gran herramienta incluso para principiantes!

Obviamente, en ámbitos en que hay internet en el aula y todas las personas tienen su computadora, este consejo es muy útil usarlo en clases presenciales también.

### Hacer un simulacro

Hagan un simulacro (con un co-docente). Quince minutos con un grupo pequeño antes de hacer una clase real (más grande) puede salvarles de decir: "No puedo compartir mi pantalla con Zoom". Acá también nosotros aprendimos esto de la peor manera cuando el día anterior a un curso cambiamos la configuración de Zoom para que tuviera más seguridad. ¡Al día siguiente, cuando la docente quería compartir la pantalla, resultó que no podía! 

### Programación en vivo presencial

La programación en vivo es una práctica útil en el aula presencial. Quien dicta la clase puede programar en su computadora mientras explica los pasos que sigue y proyecta el código en la pantalla. Sus estudiantes siguen desde su escritorio la clase y, dentro de lo posible, programan a la par.

### Programación en vivo online

La programación en vivo puede trasladarse a entornos online y no requiere mucha infraestructura. 

- Si quien dicta la clase tiene dos monitores, en uno programa a pantalla completa (pantalla compartida por el sistema de videoconferencia) y reserva la segunda pantalla para su machete, que puede ser la lección, algunas slides, sus notas… También puede ubicar en ese segundo monitor el chat y/o documento compartido.
- Si quien dicta la clase tiene un monitor, puede dedicar dos tercios de la pantalla al entorno de programación, compartiendo por videoconferencia esa ventana, y conservando abierto en el tercio restante sus notas, el chat o el documento compartido. Siempre es posible tener notas en papel, y mejor si están siempre a mano.

#### Del otro lado

¿Cómo se ve el live coding desde el lado de sus alumnos? Con dos pantallas es más fácil, porque pueden tener la clase abierta en una y su entorno de programación en la otra. Si tienen un único monitor, se divide en partes iguales entre la pantalla compartida por su docente y el entorno de programación.

## Algunos consejos

Todos los consejos que charlamos aplican perfectamente al mundo de la enseñanza online. 
Es importante establecer de antemano las expectativas y comenzar mostrando el mapa de la clase. Esto incluye no solo cuáles serán los contenidos que se presentarán, sino también cómo hacer consultas, cuándo habrá pausas y demás cuestiones organizativas.

Si estamos haciendo live coding, debemos contemplar la posibilidad de que alguien de sus estudiantes se quede atrás, no pueda resolver algún ejercicio o lo haga de forma poco eficiente. Por eso es importante compartir en el momento, o después de la clase, el código generado en vivo durante la clase. Pueden usar herramientas especiales para eso, como livecode y ngrok en R. También pueden compartir una carpeta en algún servicio de almacenamiento en la nube. Por último, como salida más rápida, pueden copiar y pegar el código en el chat o en un documento compartido.

Tengan en cuenta que programar en vivo no es fácil. Requiere práctica para hacerlo bien y tener nervios de acero para cuando las cosas no salen mal: la compu se puede trabar, puedes olvidar cuál es el siguiente paso, dudar sobre la resolución de una consulta de tus estudiantes… Siempre ayuda tener disponible un plan B para los casos en que algo sale mal.

::::::::::::::::::::::::::::::::::::: challenge 

## Ejercicio en grupo

Piensen:

- ¿Qué podría salir mal en una clase? ¿Qué soluciones/plan B se les ocurren?

- Alguna situación o experiencia propia

Una persona por grupo resumirá en el documento compartido lo que charlen 

::::::::::::::::::::::::::::::::::::::::::::::::


::::::::::::::::::::::::::::::::::::: keypoints 

- 

::::::::::::::::::::::::::::::::::::::::::::::::
